
   <div class="row jumbotron">
       <h1 style="color: #4cae4c">Кои сме ние?</h1>

       <p style='float:left; margin: 6px; '>
           <img src="<?= $SETTINGS['files_dir_url']; ?>images/water.jpg" width='300px' height='300px'/>
       </p>
       <P>
           <strong>Троян клийнинг&trade;</strong> е млада компания, създадена през 2017г.,
           която е специализирана в професионалното почистване на жилища, офиси, магазини,
           заведения, банки, хотели, административни сгради, складови помещения и др.
           Ние от <strong>Троян клийнинг&trade;</strong> работим с професионална почистваща техника на водещи производители
           като: <strong>Lavor&trade;</strong>, <strong>Nilfisk&trade;</strong>, <strong>Terrant&trade;</strong>, <strong>KCM&trade;</strong>, <strong>Ma-Fra&trade;</strong>, <strong>Karcher&trade;</strong>, <strong>Kirby</strong> и <strong>AIO&trade;</strong>.
           Използваме само екологично тествани препарати, с които Вие ще се чувствате комфортно и удобно
           във вашият дом или офис.
       </P>
   </div>
