<div class="container">
    <div class="jumbotron">
        <h1 style="color: #4cae4c">На какви цени?</h1>
        <P>
           <div class="row">
               <table id="prices-table" class="table table-bordered">
                   <caption><h2>Ценова листа:</h2></caption>
                   <thead>
                      <tr>
                         <th>Име на услугата</th>
                         <th>Цена</th>
                      </tr>
                   </thead>
                   <tbody>
                      <tr>
                         <td colspan="2"><strong>1. Стъкла, дограми и щори (едностранно)</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- стъкла и витрини до 2.5 м височина</td>
                          <td>0,70 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- дограма</td>
                          <td>0,80 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- еталбонд</td>
                          <td>0,70 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- лого</td>
                          <td>по договаряне</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- щори – алуминиеви</td>
                          <td>3,50 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- щори – ролетни</td>
                          <td>2,20 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- щори от плат</td>
                          <td>5,00 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- щори – хоризонтални (охранителни)</td>
                          <td>1,50 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td colspan="2"><strong>2. Твърди настилки</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- ръчно почистване</td>
                          <td>0,60 лв. /кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- машинно почистване</td>
                          <td>1,10 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;-  излъскване на паркет</td>
                          <td>4,20 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- почистване на цокли и первази</td>
                          <td>1,00 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td colspan="2"><strong>3. Меки настилки</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- антибактериално почистване</td>
                          <td>2,00 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- сухо машинно изпиране</td>
                          <td>2,20 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- пране на столове</td>
                          <td>3,00 лв./бр.</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- пране на тапицерии</td>
                          <td>7,00 лв. на седящо място</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- машинно изпиране на меки настилки (мокет, килим, велтер)</td>
                          <td>2,00 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td colspan="2"><strong>4. Антибактериално почистване.</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- почистване на акари</td>
                          <td>2,00 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td colspan="2"><strong>5. Почистване на санитарни помещения</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- мивка, тоалетна чиния, биде</td>
                          <td>8,00 лв./бр.</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- вана, душ кабина, джакузи</td>
                          <td>20,00 лв./бр.</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- тавани, стени и под</td>
                          <td>по договаряне</td>
                      </tr>
                      <tr>
                          <td><strong>6. Пране на тапицерии, на кола. Почистване на кола.</strong></td>
                          <td>по договаряне</td>
                      </tr>
                      <tr>
                          <td colspan="2"><strong>7. Обща работа</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- забърсване на прах</td>
                          <td>8,00 лв./ч. час</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- почистване и полиране на отделни елементи</td>
                          <td>8,00 лв./ч. час</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- почистване на врати</td>
                          <td>3,00 лв./бр.</td>
                      </tr>
                      <tr>
                          <td colspan="2"><strong>8. Ежедневна поддръжка</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- забърсване на прах</td>
                          <td>по договаряне</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- почистване на твърди настилки</td>
                          <td>по договаряне</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- прахосмукиране и измиване</td>
                          <td>по договаряне</td>
                      </tr>
                      <tr>
                          <td colspan="2"><strong>9. Транспортна такса</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- извън град Троян</td>
                          <td>0,40 лв./кв.м</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- вземане и връщане на пратка</td>
                          <td>6,00 лв</td>
                      </tr>
                      <tr>
                          <td><strong>10. Добавки върху основната цена</strong></td>
                          <td><strong>Добавка</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- след ремонт</td>
                          <td>40% – 120%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- стъкла с решетки</td>
                          <td>200%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- стени</td>
                          <td>50%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- височина над 2.50 м.</td>
                          <td>70%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- преместване на мебели</td>
                          <td>20%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- стълбища</td>
                          <td>100%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- извън работно време</td>
                          <td>50%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- почивни дни</td>
                          <td>50%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- празнични дни</td>
                          <td>50%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- нощно време</td>
                          <td>100%</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- качване и сваляне на машини</td>
                          <td>1,00лв. на етаж за машина</td>
                      </tr>
                      <tr>
                          <td><strong>11. Отстъпки</strong></td>
                          <td><strong>Отстъпкa</strong></td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- Абонаментно почистване при оглед</td>
                          <td>по договаряне</td>
                      </tr>
                      <tr>
                          <td>&nbsp;&nbsp;&nbsp;- За площ от над 100 кв.м. при оглед</td>
                          <td>по договаряне</td>
                      </tr>
                   </tbody>
               </table>
           </div>
           <div class="row">
                <span style="font-size: 13pt;"><strong style="color: #CC0000;"><u>Забележка:</u></strong> Всички цени са в BG лева, без включен ДДС.</span>
           </div>
        </P>
    </div>
</div>
