<div class="container" style="text-align: center;">

    <div id="delete_client_dialog">
        <form method="post">
        <h3>Изтриване на клиент</h3>
        <p>Сигурни ли сте, че искате да изтриете този клиент?</p>
        <p>
            <input type="submit" name="delete_yes" value="Да" /> &nbsp;
            <input type="submit" name="delete_no" value="Не" />
        </p>
        </form>
    </div>
</div>