</div>

<footer>
   <p>
      <br>
      <img src="https://s.tyxo.com/placeholder.png" width="128" height="50" alt="placeholder" class="tyxo-button" data-id="612780421646" data-token="a1C6SsAy" data-btn="22" data-font-size="12" data-bgcolor="666" data-txtcolor="FFF" data-padding="4">
   </p>
   <p>&copy; <?php echo date("Y", time()); ?> Всички права запазени</p>
</footer>

<script>
(function(i,s,o,g,r,a,m){i['TyxoObject']=r;i[r]=i[r]||function(){
(i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
})(window,document,'script','//s.tyxo.com/c.js','tx');
tx('create', 'TX-612780421646');
tx('pageview');
</script>

<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="<?= $SETTINGS['frontend_files_url'] ?>bootstrap/js/bootstrap.min.js"></script>

</body>
</html>
